name: Bug Report
description: Create a report to help us improve
title: "[Bug] "
type: bug
labels: ["Bug", "Triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Describe the steps to reproduce this bug. If applicable attach screenshots of the console at the bottom.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: media
    attributes:
      label: Screenshots / Videos
      description: If applicable, add screenshots or videos to help explain your problem.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.