"""
Collections of encoder classes to embed the graph structure into a latent space.

"""

import sys
import logging
from pathlib import Path
from typing import List, Dict, Tuple, Literal

from tqdm import tqdm

import torch
from torch import Tensor
import torch.nn as nn
import torch.nn.functional as F

from torch_geometric.nn import GATv2Conv, HeteroConv, Node2Vec, SAGEConv


logging_level = logging.INFO
logging.basicConfig(
    level = logging_level,  
    format = "%(asctime)s - %(levelname)s - %(message)s" 
)


class DefaultEncoder(nn.Module):
    """
    Encoder used by default if none is precised in the config file.
    
    This class inherits from the PyTorch `nn.module` class, without any addition:
    https://docs.pytorch.org/docs/stable/generated/torch.nn.Module.html
    
    """
    def __init__(self):
        super().__init__()



class GNN(nn.Module):
    """
    Interface for graph neural networks encoders of KGATE.

    Furthermore, this interface doesn't implement anything but is a type helper.
    However, functions from this class returning None can be used directly from inheriting classes.
    Exception for the inference_score function, fully implemented in this class.
    
    This interface inherits from the PyTorch `nn.module` class:
    https://docs.pytorch.org/docs/stable/generated/torch.nn.Module.html

    Arguments
    ---------
    edge_types: List[Tuple[str, str, str]]
        List of edge types in the form of triplets [head, tail, edge].
    aggregation: Literal["sum", "mean", "min", "max", "cat", None], default to "sum"
        The aggregation scheme to use for grouping node embeddings generated by different edges.

    Attributes
    ----------
    device: torch.device or Literal["cuda", "cpu"]
        Indicate if data should be sent to GPU or CPU.
        GPU is referenced to as Cuda.
    aggregation: Literal["sum", "mean", "min", "max", "cat", None], default to "sum"
        The aggregation scheme to use for grouping node embeddings generated by different edges.
    convolutions: nn.ModuleList()
        List of all convolutions.
        ModuleList documentation: https://docs.pytorch.org/docs/stable/generated/torch.nn.ModuleList.html
    edge_types: List[Tuple[str, str, str]]
        List of edge types in the form of triplets [head, tail, edge].
    
    """
    def __init__(self,
                edge_types: List[Tuple[str, str, str]],
                aggregation: Literal["sum", "mean", "min", "max", "cat", None] = "sum"):
        
        super().__init__()
        
        self.device = "cuda"
        self.convolutions = nn.ModuleList()
        
        # Define HeteroConv aggregation
        if aggregation in ("sum", "mean", "min", "max", "cat", None):
            self.aggregation = aggregation
        else:
            raise ValueError(f"Aggregation must be within [`sum`, `mean`, `min`, `max`, `cat`, `None`] as it is used as an argument by HeteroConv.")

        if edge_types is not None:
            node_types = []
            for triplet in edge_types:
                node_types += [triplet[0], triplet[2]]
            for node_type in set(node_types):
                edge_types.append((node_type, "self", node_type))
        self.edge_types = edge_types


    def forward(self,
                x_dict: Dict[str, Tensor],
                edge_index_dict: Dict[Tuple[str, str, str,], Tensor]
                ) -> Dict[str, Tensor]:
        """
        TODO.What_the_function_does_about_globally

        Arguments
        ---------
        x_dict: Dict[str, Tensor]
            Key (str): node type
            Value (Tensor): [node_count for the node_type, embedding_dimension]
            PyTorch Geometric equivalent to node_embeddings.
        edge_index_dict: Dict[Tuple[str, str, str,], Tensor]
            Key (Tuple[str, str, str,]): Tuple[head_type, edge_type, tail_type]
            Value (Tensor): [head_index, tail_index] for the corresponding head_type and tail_type
            PyTorch Geometric equivalent to triplet_type.

        Returns
        -------
        x_dict: Dict[str, Tensor]
            Key (str): node type
            Value (Tensor): [node_count for the node_type, embedding_dimension]
            PyTorch Geometric equivalent to node_embeddings.
            
        """
        for _, conv in enumerate(self.convolutions):
            x_dict = conv(x_dict = x_dict, edge_index_dict = edge_index_dict)
            x_dict = {key: F.leaky_relu(x) for key, x in x_dict.items()}

        return x_dict
    


class GATEncoder(GNN):
    """
    Implementation of GraphSAGE model detailed in the paper referenced below.
    
    This class inherits from the GNN class. It inherites its attributes as well.

    References
    ----------
    Shaked Brody, Uri Alon, Eran Yahav
    `How attentive are graph attention networks?`
    https://arxiv.org/abs/2105.14491
    TODO.where_got_published, 2022.

    Arguments
    ---------
    edge_types: List[Tuple[str, str, str]]
        List of edge types in the form of triplets [head, tail, edge].
    embedding_dimensions: int
        Dimensions of embedding, both of nodes and edges.
    gat_layer_count: int, default to 2
        Number of layers the convolution will be made in.
    aggregation: Literal["sum", "mean", "min", "max", "cat", None], default to "sum"
        The aggregation scheme to use for grouping node embeddings generated by different edges.
    device: torch.device or Literal["cuda", "cpu"], default to "cuda"
        Indicate if data should be sent to GPU or CPU.
        GPU is referenced to as Cuda.

    Attributes
    ----------
    layer_count: int
        Number of layers the convolution will be made in.
    edge_types: List[Tuple[str, str, str]]
        List of edge types in the form of triplets [head, tail, edge].
    aggregation: Literal["sum", "mean", "min", "max", "cat", None], default to "sum"
        The aggregation scheme to use for grouping node embeddings generated by different edges.
    convolutions: List[torch_geometric.nn.HeteroConv]
        List of all convolutions.
        Each convolution is a HeteroConv object from PyTorch Geometric.
        HeteroConv documentation: https://pytorch-geometric.readthedocs.io/en/2.7.0/generated/torch_geometric.nn.conv.HeteroConv.html
    device: torch.device or Literal["cuda", "cpu"]
        Indicate if data should be sent to GPU or CPU.
        GPU is referenced to as Cuda.
    
    """
    def __init__(self,
                edge_types: List[Tuple[str, str, str]],
                embedding_dimensions: int,
                gat_layer_count: int = 2,
                aggregation: Literal["sum", "mean", "min", "max", "cat", None] = "sum",
                device: torch.device | Literal["cuda", "cpu"] = "cuda"):
        
        super().__init__(edge_types, aggregation)
        self.layer_count = gat_layer_count

        # Define HeteroConv aggregation
        if aggregation in ("sum", "mean", "min", "max", "cat", None):
            self.aggregation = aggregation
        else:
            raise ValueError(f"Aggregation must be within [`sum`, `mean`, `min`, `max`, `cat`, `None`] as it is used as an argument by HeteroConv.")

        for _ in range(gat_layer_count):
            # Add_self_loops doesn't work on heterogeneous graphs as per https://github.com/pyg-team/pytorch_geometric/issues/8121#issuecomment-1751129825  
            convolution = HeteroConv(
                {edge_type: GATv2Conv(  in_channels = -1,
                                        out_channels = embedding_dimensions,
                                        add_self_loops = False)
                    for edge_type in self.edge_types},
                aggr = self.aggregation
                ).to(device)
            self.convolutions.append(convolution)



class GCNEncoder(GNN):
    """
    Implementation of GraphSAGE model detailed in the paper referenced below.
    
    This class inherits from the GNN class. It inherites its attributes as well.

    References
    ----------
    William L. Hamilton, Zhitao Ying and Jure Leskovec
    `Inductive Representation Learning on Large Graphs`
    https://arxiv.org/pdf/1706.02216
    In Neural Information Processing Systems, 2017.

    Arguments
    ---------
    edge_types: List[Tuple[str, str, str]]
        List of edge types in the form of triplets [head, tail, edge].
    embedding_dimensions: int
        Dimensions of embedding, both of nodes and edges.
    gcn_layer_count: int, default to 2
        Number of layers the convolution will be made in.
    aggregation: Literal["sum", "mean", "min", "max", "cat", None], default to "sum"
        The aggregation scheme to use for grouping node embeddings generated by different edges.
    device: torch.device or Literal["cuda", "cpu"], default to "cuda"
        Indicate if data should be sent to GPU or CPU.
        GPU is referenced to as Cuda.

    Attributes
    ----------
    layer_count: int
        Number of layers the convolution will be made in.
    edge_types: List[Tuple[str, str, str]]
        List of edge types in the form of triplets [head, tail, edge].
    aggregation: Literal["sum", "mean", "min", "max", "cat", None], default to "sum"
        The aggregation scheme to use for grouping node embeddings generated by different edges.
    convolutions: List[torch_geometric.nn.HeteroConv]
        List of all convolutions.
        Each convolution is a HeteroConv object from PyTorch Geometric.
        HeteroConv documentation: https://pytorch-geometric.readthedocs.io/en/2.7.0/generated/torch_geometric.nn.conv.HeteroConv.html
    device: torch.device or Literal["cuda", "cpu"]
        Indicate if data should be sent to GPU or CPU.
        GPU is referenced to as Cuda.
    
    """
    def __init__(self,
                edge_types: List[Tuple[str, str, str]],
                embedding_dimensions: int,
                gcn_layer_count: int = 2,
                aggregation: Literal["sum", "mean", "min", "max", "cat", None] = "sum",
                device: torch.device | Literal["cuda", "cpu"] = "cuda"):
        
        super().__init__(edge_types, aggregation)
        self.layer_count = gcn_layer_count
        
        # Define HeteroConv aggregation
        if aggregation in ("sum", "mean", "min", "max", "cat", None):
            self.aggregation = aggregation
        else:
            raise ValueError(f"Aggregation must be within [`sum`, `mean`, `min`, `max`, `cat`, `None`] as it is used as an argument by HeteroConv.")

        for _ in range(gcn_layer_count):
            convolution = HeteroConv(
                {edge_type: SAGEConv(   in_channels = -1,
                                        out_channels = embedding_dimensions,
                                        aggregation = "mean")
                    for edge_type in self.edge_types},
                aggr = self.aggregation
                ).to(device)
            self.convolutions.append(convolution)



class Node2VecEncoder:
    """
    Implementation of node2vec model detailed in the paper referenced below.

    References
    ----------
    Aditya Grover, Jure Leskovec
    `node2vec: Scalable Feature Learning for Networks`
    https://arxiv.org/pdf/1607.00653
    In Proceedings of the 22nd ACM SIGKDD International Conference on Knowledge Discovery and Data Mining, 2016.

    Arguments
    ---------
    edge_indices: torch.Tensor
        Indices of edges.
    embedding_dimensions: int
        Dimensions of embedding, both of nodes and edges.
    walk_length: int
        The walk length.
    context_size: int
        The actual context size which is considered for positive samples.
        This parameter increases the effective sampling rate by reusing samples across different source nodes.
    device: torch.device or Literal["cuda", "cpu"]
        Indicate if data should be sent to GPU or CPU.
        GPU is referenced to as Cuda.
    output_directory: Path
        Path to the directory where files will be created.

    Attributes
    ----------
    device: torch.device or Literal["cuda", "cpu"]
        Indicate if data should be sent to GPU or CPU.
        GPU is referenced to as Cuda.
    output_directory: Path
        Path to the directory where files will be created.
    model: torch_geometric.nn.Node2Vec
        The Node2Vec model object.
        Node2Vec documentation: https://pytorch-geometric.readthedocs.io/en/2.5.1/generated/torch_geometric.nn.models.Node2Vec.html
    loader: TODO.type
        TODO.What_that_variable_is_or_does
    optimizer: TODO.type
        TODO.What_that_variable_is_or_does
    
    """
    def __init__(self,
                edge_indices: Tensor,
                embedding_dimensions: int,
                walk_length: int,
                context_size: int,
                output_directory: Path,
                device: torch.device | Literal["cuda", "cpu"] = "cuda",
                **node2vec_kwargs):
        self.device = device
        self.output_directory = output_directory
        self.model = Node2Vec(
            edge_index = edge_indices,
            embedding_dim = embedding_dimensions,
            walk_length = walk_length,
            context_size = context_size,
            **node2vec_kwargs
            ).to(device)

        workers_count = 4 if sys.platform == 'linux' else 0
        self.loader = self.model.loader(batch_size = 128, shuffle = True, num_workers = workers_count)
        self.optimizer = torch.optim.SparseAdam(list(self.model.parameters()), lr = 0.01)
    
    
    def generate_embeddings(self):
        """
        TODO.What_the_function_does_about_globally
        
        """
        for epoch in range(1,101):
            epoch_loss = 0
            for positive_random_walk, negative_random_walk in tqdm(self.loader):
                self.optimizer.zero_grad()
                loss = self.model.loss(positive_random_walk.to(self.device), negative_random_walk.to(self.device))
                loss.backward()
                self.optimizer.step()
                epoch_loss += loss.item()
            
            logging.info(f"Epoch {epoch: 03d}, Embedding Loss: {loss: .4f}")

        torch.save(self.model.embedding, self.output_directory.joinpath("embeddings_node2vec.pt"))
        logging.info(f"Embedding fully generated, saved in {self.output_directory}")